### PR TITLE
Overrides custom `templates` and `static` files from your docker volume while developing

### LINKED ISSUE #61: Allow `config/g3w-suite/overrides/static` usage while developing
As per v3.4 it is only possible to override templates (ref: https://github.com/g3w-suite/g3w-suite-docker/pull/58):

https://github.com/g3w-suite/g3w-suite-docker/blob/c37f17d518ee7dda8654bb1b85e2c02a241681ed/docker-compose-dev.yml#L69

during development it would also be handy to allow overriding of static files, as it already happens for the `docker-compose.yml` file:

https://github.com/g3w-suite/g3w-suite-docker/blob/c37f17d518ee7dda8654bb1b85e2c02a241681ed/docker-compose.yml#L81

### PR DESCRIPTION
**Pull request by Raruto**
Load custom templates and static files from your docker volume (eg. `./config/g3w-suite/overrides/`)

- https://docs.djangoproject.com/en/2.2/howto/overriding-templates/
- https://docs.djangoproject.com/en/2.2/howto/static-files/
- https://docs.djangoproject.com/en/2.2/topics/settings/

Currently tested only with the edited `docker-compose-dev.yml` (but it shouldn't create any major collateral problems).

---

**NB** it make use of:

```py
from django.conf import settings
```
instead of:

```py
from base.settings.base import TEMPLATES, BASE_DIR, STATICFILES_DIRS 
```

so default django values are safely used as a fallback (eg. `STATICFILES_DIRS = []`)

Close https://github.com/g3w-suite/g3w-suite-docker/issues/61

### CODE REVIEW

**Comment by Raruto** [comment]
@wlorenzetti wait a moment before merge this, I have to check something before

**Comment by wlorenzetti** [comment]
Don't worry, now I'm on preparations for FOSS4G.

**Comment by Raruto** [comment]
@wlorenzetti https://github.com/g3w-suite/g3w-client/pull/150 depends heavily on this changes, could you test this pull (and eventually approve) so we are quite ready to release **`g3w-client@v3.7.0-beta`**?

**Comment by Raruto** [comment]
@wlorenzetti any negative notes about it? (otherwise if you can merge this, for client development this is a time saver ...)

**Review by wlorenzetti — APPROVED** [review]
@Raruto I just try on production docker-compose.yml  and works fine.

**Pull request merged**
