### PR TITLE
Lucamanga patch 1

### PR DESCRIPTION
**Pull request by lucamanga**
New environment variable G3WSUITE_GUNICORN_TIMEOUT, to set the gunicorn timeout for X seconds, other than the default value of 120. In some cases, the default value is not sufficient while working with many projects, especially if these projects are using embedded layers.

### CODE REVIEW

**Comment by wlorenzetti** [comment]
Thanks @lucamanga :)

**Comment by lucamanga** [comment]
This patch can be pushed to 3.4 branch, too 😄

**Comment by wlorenzetti** [comment]
Can you make another PR on branch v3.4.x?

**Comment by lucamanga** [comment]
> Can you make another PR on branch v3.4.x?

OK!

**Comment by lucamanga** [comment]
Done!

**Pull request merged**
