### PR TITLE
Add the new qgis.org key using the simpler approach, also update the rest of the dockerfiles

### PR DESCRIPTION
**Pull request by tudorbarascu**
Hello,

Simply updated the qgis.org key to all the docker files + fix a bionic -> focal typo

### CODE REVIEW

**Comment by wlorenzetti** [comment]
Thanks @tudorbarascu, but follow qgis.org instruction key come from qgis.org site, is it correct?

**Comment by wlorenzetti** [comment]
> While at it, I don't understand the difference beetween Dockerfile.g3wsuite-deps.dockerfile and Dockerfile.g3wsuite-deps.dockerfile and Dockerfile.g3wsuite-deps.ltr.dockerfile as they're the same, so why should both be kept?

Simple @tudorbarascu, g3w-suite-deps il for last QGIS version available, now is 3.26 instead ltr is for last fersion for  QGIS LTR edition 3.22. Into Continue Integration no LTR version is used to test with new API.

**Comment by tudorbarascu** [comment]
> Thanks @tudorbarascu, but follow qgis.org instruction key come from qgis.org site, is it correct?

Yes, that's the general instruction for linux. It seems that Tim puts all the time the new key to the keyserver.ubuntu.com as you can see from https://keyserver.ubuntu.com/pks/lookup?search=qgis.org&fingerprint=on&op=index 

So for ubuntu the key steps are easier and as the docker images are for ubuntu I thought its simpler as it was before. Thank you

**Comment by wlorenzetti** [comment]
@tudorbarascu I didn't Tim enetered kye on official Ubuntu key-server. Thanks.

**Pull request merged**
